name: test

on: [ push ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x', '20.x']
        command: ['node ./request.mjs', 'npm run vitest']
        preferIpv4: [true, false]
        disableIpv6: [true, false]
      fail-fast: false
    steps:
      -
        name: Prefer Ipv4
        if: ${{ matrix.preferIpv4 }}
        run: sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
      -
        name: Disable Ipv6
        if: ${{ matrix.disableIpv6 }}
        run: |-
          sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sysctl -w net.ipv6.conf.lo.disable_ipv6=1
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Test
        run: ${{ matrix.command }}